name: Test and deploy to Heroku

on:
  push:
    # branches: [master]

jobs:
  test:
    uses: SinxRofozoteron/react-resume/.github/workflows/Test.yml@1db559ec62269f6945372d4d56b3760482d5df37
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into master branch
        uses: actions/checkout@v2.3.5
      - name: Set node version to be v15.10.0
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "v15.10.0"
      - name: Set Yarn version
        run: yarn set version 1.22.10
      - name: Install dependancies
        run: |
          yarn install --frozen-lockfile
          cd client
          yarn install --frozen-lockfile
      - name: Build
        run: |
          tsc
          cd client
          yarn build
      - name: Save Build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: |
            ./dist
            ./client/build
            ./package.json
  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: production-build
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Login To Heroku
        run: heroku auth:whoami
